### PR TITLE
Add OVH Logs Data Platform compatibility handler

### PR DESCRIPTION
**Pull request by olopost**
I add a compatibility handler for OVH Logs Data Platform

### CODE REVIEW

**Comment by keeprocking** [comment]
Thanks a lot, will give it a look when I get back from the vacation (somewhat next week).

Cheers.

**Comment by keeprocking** [comment]
Hey,

Really sorry for the delay on this.

Just checked the patch and from what I see, the functionality being added can be achieved some other way, without introducing a new handler: you can pass the OVH API token as static field via `additional_fields` argument: https://github.com/keeprocking/pygelf#static-fields

Is there any reason to add a new handler?

**Comment by olopost** [comment]
Hi Ivan,

Of course I try the additional fields that’s an awesome feature.

But due to the dash in OVH API TOKEN, I need to override it’s transmission

Best regards

— 
Samuel MEYNARD

**Comment by keeprocking** [comment]
Then I'm afraid the patch won't help because the `_field -> field` conversion is made on Graylog side, pygelf has nothing to do with it.

Could you please check if passing a `__X_OVH_TOKEN` (with 2 underscores in front) would help?

Also, what is your case? Probably there's another solution and I could help you.

**Comment by keeprocking** [comment]
Sorry, I meant `__X-OVH-TOKEN`, of course

**Comment by keeprocking** [comment]
Found an example of using GELF and OVH together: https://docs.ovh.com/gb/en/logs-data-platform/quick-start/

Since the field `X-OVH-TOKEN` must be passed as is, without any leading underscores, the proposed way (using `additional_fields`) should work.

Could you please elaborate what exactly does not work?

**Comment by olopost** [comment]
Thanks Ivan, I will test your proposal with double underscore this weekend.
My first test with double underscore and dash seem not working, the name is not resolve after first dash (seem due by the fact that python interpret the dash as minus sign).
That’s the reason why that I pass directly this information in the dict in my submission.

Best regards Ivan
-- 
Samuel MEYNARD
✉ : samuel@meyn.fr
✆ : 06.09.66.07.43

**Comment by keeprocking** [comment]
Hey @olopost, is this still actual?

**Pull request merged**
